# Generated by Django 3.1.7 on 2021-08-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_log1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log1',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='log1',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='log1',
            old_name='username',
            new_name='username1',
        ),
    ]
