# Generated by Django 3.1.7 on 2021-08-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.ManyToManyField(to='app.log'),
        ),
    ]
