# Generated by Django 3.1.7 on 2021-08-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('subjectname', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=800)),
                ('time', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('subjectname', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=800)),
                ('time', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='marks',
        ),
    ]
