# Generated by Django 3.1.7 on 2021-08-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210830_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='email',
            new_name='email3',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='question',
            new_name='question3',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='subjectname',
            new_name='subjectname3',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='time',
            new_name='time3',
        ),
    ]
