# Generated by Django 3.1.7 on 2021-08-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210830_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tes',
            new_name='testtable',
        ),
    ]
