# Generated by Django 3.1.7 on 2021-08-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210830_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='question3',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='subjectname3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='time3',
            field=models.CharField(default='', max_length=30),
        ),
    ]
