# Generated by Django 3.1.7 on 2021-08-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210831_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='subjectname3',
            field=models.CharField(max_length=30),
        ),
    ]
