# Generated by Django 3.1.7 on 2021-08-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
